project:
  type: website

website: 
  title: "Data Analysis"
  navbar: 
    tools:
      - icon: github
        href: https://github.com/aravindsankars/myData_Analysis
    left:
      - text: "Netflix titles COVID Comparison"
        menu:
          - index.qmd
          - intro.qmd
          - analysis.qmd
      - text: "Case Study for Cyclistic"
        menu:
          - question.qmd
          - case.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    toc: true
