project:
  type: website

website: 
  title: "Data Analysis"
  navbar: 
    tools:
      - icon: github
        href: https://github.com/aravindsankars/myData_Analysis


format:
  html:
    theme:
      light: minty
      dark: slate
    toc: true
