project:
  type: website

website: 
  title: "Data Analysis"
  navbar: 
    tools:
      - icon: github
        href: https://github.com/aravindsankars/myData_Analysis
    left:
      - text: "Netflix titles COVID Comparison"
        menu:
          - index.qmd
          - analysis.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    toc: true

output-dir: _site
homepage: intro.qmd