---
title: "Data Analysis Portfolio"
format: html
---

---
title: "Data Analysis Portfolio"
format: html
---

# Cyclistic rider analysis 🚴💼

Cyclistic, a bike-share company, seeks to understand how annual members and casual riders use its service. This case study explores usage patterns, preferences, and behavioral differences to inform targeted marketing and operational strategies.

The primary question addressed is: *How do annual members and casual riders use Cyclistic bikes differently?*

Using visualizations, I uncover key trends in ride frequency, duration, and time-based usage, with detailed explanations and insights accompanying each analysis.

[Refer to the attached case study notebook](posts/Analysis_v03.ipynb) for a detailed analysis.

[Refer to the attached problem statement](posts/Case_Study_How_does_a_bike-shared_navigate_speedy_success_.pdf) for better understanding of the problem statement for the case study.

---

# Netflix Titles: COVID Analysis 🍿🎥

The impact of COVID-19 has been profound across industries, and the entertainment field is no exception. 
As someone with a long-standing interest in movies and a curiosity about Netflix's business strategy, I was particularly intrigued by how the streaming giant adapted its content library in response to the pandemic.

This project is an effort to explore the changes in Netflix's movie catalog by comparing data from the pre-COVID and post-COVID periods.

[Refer to the data preparation notebook](posts/TMDb_Netflix_Connect_Notebook.ipynb) for the data preparation part for the project.

[Refer to the analysis and visualizations notebook](posts/Analysis_Visualization.ipynb) for the detailed analysis and visualizations part for the project.

---


